language: python
python:
  - "3.5"
  - "3.6"
  
matrix:
  include: # thats the official workaround until they fix it
    - python: 3.7
      dist: xenial
      sudo: true
  allow_failures:
    - python: "3.5"
    - python: "3.7"
  fast_finish: true

# command to install dependencies
install:
  - pip uninstall -y numpy
  - pip install --upgrade pip
  - python setup.py install

# command to run tests
script:
  - nosetests --nologcapture -w Tests/

notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
